version: "3"

dotenv: [".env"]

env:
  WORK_DIR: ./build
  GITHUB_REPO: https://github.com/Nandaka/PixivUtil2

tasks:
  prepare:
    desc: "Create working directory and fetch source code"
    cmds:
      - rm -rf {{.WORK_DIR}}
      - mkdir {{.WORK_DIR}}
      - |
        curl -L {{.GITHUB_REPO}}/archive/refs/heads/master.tar.gz | \
        tar -xz --strip-components=1 -C {{.WORK_DIR}}
      - cp -r app/. {{.WORK_DIR}}/
    silent: true

  build:
    cmds:
      - task: prepare
      - task: amd
      - docker buildx imagetools create -t ${REGISTRY}/${APP_NAME}:latest ${REGISTRY}/${APP_NAME}:amd
      - ssh ${REMOTE_HOST} "docker pull ${REGISTRY}/${APP_NAME}:latest"
      - say -v Samantha "The Docker build is complete."

  amd:
    internal: true
    dir: "{{.WORK_DIR}}"
    cmds:
      - |
        docker buildx build \
          --builder ${AMD64_BUILDER} \
          --platform linux/amd64 \
          --build-arg apt_cacher=${APT_CACHER} \
          --push \
          -t ${REGISTRY}/${APP_NAME}:amd .
    silent: true

  arm:
    internal: true
    dir: "{{.WORK_DIR}}"
    cmds:
      - |
        docker buildx build \
          --platform linux/arm64 \
          --build-arg apt_cacher=${APT_CACHER} \
          --push \
          -t ${REGISTRY}/${APP_NAME}:arm .
    silent: true
